export const cities = [
  { value: "1642911", label: "Jakarta" },
  { value: "1625822", label: "Surabaya" },
  { value: "1636722", label: "Bandung" },
  { value: "1622786", label: "Medan" },
  { value: "1627896", label: "Semarang" },
  { value: "1650357", label: "Makassar" },
  { value: "1649378", label: "Palembang" },
  { value: "1625084", label: "Tangerang" },
  { value: "1651944", label: "Depok" },
  { value: "1621836", label: "Bekasi" },
  { value: "1630344", label: "Malang" },
  { value: "1621177", label: "Padang" },
  { value: "1633419", label: "Pekanbaru" },
  { value: "1645524", label: "Bogor" },
  { value: "1624964", label: "Denpasar" },
  { value: "1623459", label: "Batam" },
  { value: "1643837", label: "Banjarmasin" },
  { value: "1626542", label: "Samarinda" },
  { value: "1623197", label: "Pontianak" },
  { value: "1630789", label: "Manado" },
  { value: "1634215", label: "Mataram" },
  { value: "1634614", label: "Kupang" },
  { value: "1633418", label: "Ambon" },
  { value: "1625738", label: "Ternate" },
  { value: "1621597", label: "Jayapura" },
  { value: "1626493", label: "Sukabumi" },
  { value: "1629001", label: "Cirebon" },
  { value: "1649150", label: "Palu" },
  { value: "1635111", label: "Jambi" },
  { value: "1636022", label: "Kendari" }
];

export const cropdata = [
  {
    "crop": {
      "name": "Rice",
      "qnt": "30"
    },
    "sold_at": 3200,
    "expense": {
      "seeds": 600,
      "fertilizers": [
        {
          "name": "DAP",
          "cost": 350
        },
        {
          "name": "Potash",
          "cost": 270
        }
      ],
      "electricity": 500,
      "machinery": 900,
      "labor": 600,
      "water_usage": 1100,
      "storage": 400,
      "transport": 500,
      "pesticides": [
        {
          "name": "Chlorpyrifos",
          "cost": 200
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Barley",
      "qnt": "15"
    },
    "sold_at": 2100,
    "expense": {
      "seeds": 450,
      "fertilizers": [
        {
          "name": "Urea",
          "cost": 280
        },
        {
          "name": "Ammonium Nitrate",
          "cost": 300
        }
      ],
      "electricity": 450,
      "machinery": 850,
      "labor": 500,
      "water_usage": 1050,
      "storage": 300,
      "transport": 400,
      "pesticides": [
        {
          "name": "Malathion",
          "cost": 180
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Maize",
      "qnt": "25"
    },
    "sold_at": 2900,
    "expense": {
      "seeds": 550,
      "fertilizers": [
        {
          "name": "NPK",
          "cost": 320
        },
        {
          "name": "Sulphate",
          "cost": 260
        }
      ],
      "electricity": 470,
      "machinery": 900,
      "labor": 620,
      "water_usage": 1150,
      "storage": 450,
      "transport": 420,
      "pesticides": [
        {
          "name": "Permethrin",
          "cost": 160
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Soybean",
      "qnt": "18"
    },
    "sold_at": 3400,
    "expense": {
      "seeds": 650,
      "fertilizers": [
        {
          "name": "Phosphorus",
          "cost": 310
        },
        {
          "name": "Ammonium Sulfate",
          "cost": 290
        }
      ],
      "electricity": 490,
      "machinery": 920,
      "labor": 570,
      "water_usage": 1250,
      "storage": 380,
      "transport": 430,
      "pesticides": [
        {
          "name": "Cypermethrin",
          "cost": 175
        }
      ]
    }
  },
  {
    "crop": {
      "name": "Oats",
      "qnt": "20"
    },
    "sold_at": 2800,
    "expense": {
      "seeds": 500,
      "fertilizers": [
        {
          "name": "Nitrogen",
          "cost": 270
        },
        {
          "name": "Lime",
          "cost": 250
        }
      ],
      "electricity": 430,
      "machinery": 890,
      "labor": 560,
      "water_usage": 1120,
      "storage": 360,
      "transport": 410,
      "pesticides": [
        {
          "name": "Lambda-Cyhalothrin",
          "cost": 140
        }
      ]
    }
  }
];


export const countryCodes = [
  { code: "+1", country: "🇺🇸 United States" },
  { code: "+44", country: "🇬🇧 United Kingdom" },
  { code: "+91", country: "🇮🇳 India" },
  { code: "+86", country: "🇨🇳 China" },
  { code: "+81", country: "🇯🇵 Japan" },
  { code: "+49", country: "🇩🇪 Germany" },
  { code: "+33", country: "🇫🇷 France" },
  { code: "+39", country: "🇮🇹 Italy" },
  { code: "+7", country: "🇷🇺 Russia" },
  { code: "+55", country: "🇧🇷 Brazil" },
  { code: "+52", country: "🇲🇽 Mexico" },
  { code: "+34", country: "🇪🇸 Spain" },
  { code: "+61", country: "🇦🇺 Australia" },
  { code: "+1", country: "🇨🇦 Canada" },
  { code: "+82", country: "🇰🇷 South Korea" },
  { code: "+31", country: "🇳🇱 Netherlands" },
  { code: "+90", country: "🇹🇷 Turkey" },
  { code: "+46", country: "🇸🇪 Sweden" },
  { code: "+41", country: "🇨🇭 Switzerland" },
  { code: "+65", country: "🇸🇬 Singapore" },
  { code: "+27", country: "🇿🇦 South Africa" },
  { code: "+54", country: "🇦🇷 Argentina" },
  { code: "+20", country: "🇪🇬 Egypt" },
  { code: "+66", country: "🇹🇭 Thailand" },
  { code: "+92", country: "🇵🇰 Pakistan" },
  { code: "+62", country: "🇮🇩 Indonesia" },
  { code: "+84", country: "🇻🇳 Vietnam" },
  { code: "+60", country: "🇲🇾 Malaysia" },
  { code: "+63", country: "🇵🇭 Philippines" },
  { code: "+64", country: "🇳🇿 New Zealand" },
  { code: "+43", country: "🇦🇹 Austria" },
  { code: "+32", country: "🇧🇪 Belgium" },
  { code: "+45", country: "🇩🇰 Denmark" },
  { code: "+358", country: "🇫🇮 Finland" },
  { code: "+30", country: "🇬🇷 Greece" },
  { code: "+353", country: "🇮🇪 Ireland" },
  { code: "+972", country: "🇮🇱 Israel" },
  { code: "+47", country: "🇳🇴 Norway" },
  { code: "+351", country: "🇵🇹 Portugal" },
  { code: "+48", country: "🇵🇱 Poland" },
  { code: "+40", country: "🇷🇴 Romania" },
  { code: "+36", country: "🇭🇺 Hungary" },
  { code: "+420", country: "🇨🇿 Czech Republic" },
  { code: "+56", country: "🇨🇱 Chile" },
  { code: "+57", country: "🇨🇴 Colombia" },
  { code: "+58", country: "🇻🇪 Venezuela" },
  { code: "+51", country: "🇵🇪 Peru" },
  { code: "+971", country: "🇦🇪 United Arab Emirates" },
  { code: "+966", country: "🇸🇦 Saudi Arabia" },
  { code: "+98", country: "🇮🇷 Iran" },
  { code: "+880", country: "🇧🇩 Bangladesh" },
  { code: "+234", country: "🇳🇬 Nigeria" },
  { code: "+254", country: "🇰🇪 Kenya" },
  { code: "+380", country: "🇺🇦 Ukraine" },
  { code: "+359", country: "🇧🇬 Bulgaria" },
  { code: "+385", country: "🇭🇷 Croatia" },
  { code: "+381", country: "🇷🇸 Serbia" },
  { code: "+352", country: "🇱🇺 Luxembourg" },
  { code: "+356", country: "🇲🇹 Malta" },
  { code: "+354", country: "🇮🇸 Iceland" },
  { code: "+371", country: "🇱🇻 Latvia" },
  { code: "+370", country: "🇱🇹 Lithuania" },
  { code: "+372", country: "🇪🇪 Estonia" },
  { code: "+373", country: "🇲🇩 Moldova" },
  { code: "+377", country: "🇲🇨 Monaco" },
  { code: "+376", country: "🇦🇩 Andorra" },
  { code: "+423", country: "🇱🇮 Liechtenstein" },
  { code: "+386", country: "🇸🇮 Slovenia" },
  { code: "+421", country: "🇸🇰 Slovakia" },
  { code: "+598", country: "🇺🇾 Uruguay" },
  { code: "+593", country: "🇪🇨 Ecuador" },
  { code: "+503", country: "🇸🇻 El Salvador" },
  { code: "+502", country: "🇬🇹 Guatemala" },
  { code: "+504", country: "🇭🇳 Honduras" },
  { code: "+506", country: "🇨🇷 Costa Rica" },
  { code: "+507", country: "🇵🇦 Panama" },
  { code: "+595", country: "🇵🇾 Paraguay" },
  { code: "+591", country: "🇧🇴 Bolivia" },
  { code: "+962", country: "🇯🇴 Jordan" },
  { code: "+961", country: "🇱🇧 Lebanon" },
  { code: "+968", country: "🇴🇲 Oman" },
  { code: "+974", country: "🇶🇦 Qatar" },
  { code: "+965", country: "🇰🇼 Kuwait" },
  { code: "+973", country: "🇧🇭 Bahrain" },
  { code: "+994", country: "🇦🇿 Azerbaijan" },
  { code: "+995", country: "🇬🇪 Georgia" },
  { code: "+993", country: "🇹🇲 Turkmenistan" },
  { code: "+998", country: "🇺🇿 Uzbekistan" },
  { code: "+996", country: "🇰🇬 Kyrgyzstan" },
  { code: "+977", country: "🇳🇵 Nepal" },
  { code: "+94", country: "🇱🇰 Sri Lanka" },
  { code: "+95", country: "🇲🇲 Myanmar" },
  { code: "+855", country: "🇰🇭 Cambodia" },
  { code: "+856", country: "🇱🇦 Laos" },
  { code: "+976", country: "🇲🇳 Mongolia" },
  { code: "+850", country: "🇰🇵 North Korea" },
  { code: "+853", country: "🇲🇴 Macau" },
  { code: "+852", country: "🇭🇰 Hong Kong" },
  { code: "+886", country: "🇹🇼 Taiwan" },
  { code: "+673", country: "🇧🇳 Brunei" },
  { code: "+670", country: "🇹🇱 East Timor" },
  { code: "+675", country: "🇵🇬 Papua New Guinea" },
  { code: "+679", country: "🇫🇯 Fiji" },
  { code: "+687", country: "🇳🇨 New Caledonia" },
  { code: "+689", country: "🇵🇫 French Polynesia" },
];

export const district = [
  "KABUPATEN ACEH BESAR",
  "KOTA BANDA ACEH",
  "KABUPATEN DELI SERDANG",
  "KOTA MEDAN",
  "KABUPATEN AGAM",
  "KOTA PADANG",
  "KABUPATEN OGAN KOMERING ILIR",
  "KOTA PALEMBANG",
  "KABUPATEN LEBAK",
  "KOTA SERANG",
  "KABUPATEN BOGOR",
  "KOTA DEPOK",
  "KOTA JAKARTA SELATAN",
  "KOTA JAKARTA BARAT",
  "KOTA JAKARTA TIMUR",
  "KOTA JAKARTA PUSAT",
  "KOTA JAKARTA UTARA",
  "KABUPATEN BEKASI",
  "KOTA BEKASI",
  "KABUPATEN KARAWANG",
  "KOTA BANDUNG",
  "KABUPATEN CIAMIS",
  "KOTA CIREBON",
  "KABUPATEN SEMARANG",
  "KOTA SEMARANG",
  "KOTA SURAKARTA",
  "KABUPATEN BANTUL",
  "KOTA YOGYAKARTA",
  "KABUPATEN MALANG",
  "KOTA MALANG",
  "KOTA SURABAYA",
  "KABUPATEN GIANYAR",
  "KOTA DENPASAR",
  "KABUPATEN LOMBOK BARAT",
  "KOTA MATARAM",
  "KABUPATEN KUTAI KARTANEGARA",
  "KOTA BALIKPAPAN",
  "KOTA SAMARINDA",
  "KABUPATEN BERAU",
  "KABUPATEN BONE",
  "KOTA MAKASSAR",
  "KOTA PAREPARE",
  "KABUPATEN MOROWALI",
  "KOTA PALU",
  "KABUPATEN MANOKWARI",
  "KOTA SORONG",
  "KABUPATEN MERAUKE",
  "KOTA JAYAPURA"
];

// export const crop = [
//   "Arcanut (Processed)",
//   "Arecanut",
//   "Arhar/Tur",
//   "Atcanut (Raw)",
//   "Bajra",
//   "Banana",
//   "Barley",
//   "Beans & Mutter(Vegetable)",
//   "Bhindi",
//   "Bitter Gourd",
//   "Black pepper",
//   "Blackgram",
//   "Bottle Gourd",
//   "Brinjal",
//   "Cabbage",
//   "Cardamom",
//   "Carrot",
//   "Cashewnut",
//   "Cashewnut Processed",
//   "Cashewnut Raw",
//   "Castor seed",
//   "Citrus Fruit",
//   "Coconut",
//   "Coffee",
//   "Cond-spcs other",
//   "Coriander",
//   "Cotton(lint)",
//   "Cowpea(Lobia)",
//   "Cucumber",
//   "Drum Stick",
//   "Dry chillies",
//   "Dry ginger",
//   "Garlic",
//   "Ginger",
//   "Gram",
//   "Grapes",
//   "Groundnut",
//   "Guar seed",
//   "Horse-gram",
//   "Jack Fruit",
//   "Jowar",
//   "Jute",
//   "Khesari",
//   "Korra",
//   "Lemon",
//   "Linseed",
//   "Maize",
//   "Mango",
//   "Masoor",
//   "Mesta",
//   "Moong(Green Gram)",
//   "Moth",
//   "Niger seed",
//   "Oilseeds total",
//   "Onion",
//   "Orange",
//   "Other  Rabi pulses",
//   "Other Cereals & Millets",
//   "Other Fresh Fruits",
//   "Other Indonesian pulses",
//   "Other Vegetables",
//   "Paddy",
//   "Papaya",
//   "Peas  (vegetable)",
//   "Peas & beans (Pulses)",
//   "Pineapple",
//   "Pome Fruit",
//   "Pome Granet",
//   "Potato",
//   "Pulses total",
//   "Pump Kin",
//   "Ragi",
//   "Rapeseed &Mustard",
//   "Redish",
//   "Rice",
//   "Rubber",
//   "Safflower",
//   "Samai",
//   "Sannhamp",
//   "Sapota",
//   "Sesamum",
//   "Small millets",
//   "Snak Guard",
//   "Soyabean",
//   "Sugarcane",
//   "Sunflower",
//   "Sweet potato",
//   "Tapioca",
//   "Tea",
//   "Tobacco",
//   "Tomato",
//   "Turmeric",
//   "Turnip",
//   "Urad",
//   "Varagu",
//   "Wheat",
//   "other fibres",
//   "other misc. pulses",
//   "other oilseeds",
// ];

export const crop = [
  "Padi",
  "Jagung",
  "Kedelai",
  "Ubi Jalar",
  "Singkong",
  "Kentang",
]

export const season = ["Kemarau", "Hujan", "Pancaroba"];

export const kabkot = ['Kab. Aceh Tengah',
 'Kab. Aceh Barat',
 'Kab. Aceh Tamiang',
 'Kota Banda Aceh',
 'Kota Lhokseumawe',
 'Kab. Karo',
 'Kab. Deli Serdang',
 'Kab. Labuhanbatu',
 'Kota Medan',
 'Kota Pematangsiantar',
 'Kota Sibolga',
 'Kota Padang Sidempuan',
 'Kota Gunungsitoli',
 'Kab. Dharmasraya',
 'Kab. Pasaman Barat',
 'Kota Padang',
 'Kota Bukittinggi',
 'Kab. Kampar',
 'Kab. Indragiri Hilir',
 'Kota Pekanbaru',
 'Kota Dumai',
 'Kab. Kerinci',
 'Kab. Bungo',
 'Kota Jambi',
 'Kab. Ogan Komering Ilir',
 'Kab. Muara Enim',
 'Kota Palembang',
 'Kota Lubuk Linggau',
 'Kab. Muko Muko',
 'Kota Bengkulu',
 'Kab. Lampung Timur',
 'Kab. Mesuji',
 'Kota Bandar Lampung',
 'Kota Metro',
 'Kab. Belitung',
 'Kab. Bangka Barat',
 'Kab. Belitung Timur',
 'Kota Pangkal Pinang',
 'Kab. Karimun',
 'Kota Batam',
 'Kota Tanjung Pinang',
 'Kota Adm. Jakarta Pusat',
 'Kota Adm. Jakarta Utara',
 'Kota Adm. Jakarta Barat',
 'Kota Adm. Jakarta Selatan',
 'Kota Adm. Jakarta Timur',
 'Kab. Bandung',
 'Kab. Majalengka',
 'Kab. Subang',
 'Kota Bogor',
 'Kota Sukabumi',
 'Kota Bandung',
 'Kota Cirebon',
 'Kota Bekasi',
 'Kota Depok',
 'Kota Tasikmalaya',
 'Kab. Cilacap',
 'Kab. Banyumas',
 'Kab. Wonosobo',
 'Kab. Wonogiri',
 'Kab. Rembang',
 'Kab. Kudus',
 'Kota Surakarta',
 'Kota Semarang',
 'Kota Tegal',
 'Kab. Gunungkidul',
 'Kota Yogyakarta',
 'Kab. Tulungagung',
 'Kab. Jember',
 'Kab. Banyuwangi',
 'Kab. Bojonegoro',
 'Kab. Gresik',
 'Kab. Sumenep',
 'Kota Kediri',
 'Kota Malang',
 'Kota Probolinggo',
 'Kota Madiun',
 'Kota Surabaya',
 'Kab. Pandeglang',
 'Kab. Lebak',
 'Kota Tangerang',
 'Kota Cilegon',
 'Kota Serang',
 'Kab. Tabanan',
 'Kab. Badung',
 'Kab. Buleleng',
 'Kota Denpasar',
 'Kab. Sumbawa',
 'Kota Mataram',
 'Kota Bima',
 'Kab Timor Tengah Selatan',
 'Kab. Sikka',
 'Kab. Ngada',
 'Kab. Sumba Timur',
 'Kota Kupang',
 'Kab. Ketapang',
 'Kab. Sintang',
 'Kab. Kayong Utara',
 'Kota Pontianak',
 'Kota Singkawang',
 'Kab. Kotawaringin Timur',
 'Kab. Kapuas',
 'Kab. Sukamara',
 'Kota Palangkaraya',
 'Kab. Tanah Laut',
 'Kab. Kotabaru',
 'Kab. Hulu Sungai Tengah',
 'Kab. Tabalong',
 'Kota Banjarmasin',
 'Kab. Berau',
 'Kab. Penajam Paser Utara',
 'Kota Balikpapan',
 'Kota Samarinda',
 'Kab. Bulungan',
 'Kab. Nunukan',
 'Kota Tarakan',
 'Kab. Minahasa Selatan',
 'Kab. Minahasa Utara',
 'Kota Manado',
 'Kota Kotamobagu',
 'Kab. Banggai',
 'Kab. Toli Toli',
 'Kab. Morowali',
 'Kota Palu',
 'Kab. Bulukumba',
 'Kab. Bone',
 'Kab. Wajo',
 'Kab. Sidenreng Rappang',
 'Kab. Luwu Timur',
 'Kota Makassar',
 'Kota Pare Pare',
 'Kota Palopo',
 'Kab. Kolaka',
 'Kab. Konawe',
 'Kota Kendari',
 'Kota Bau Bau',
 'Kab. Gorontalo',
 'Kota Gorontalo',
 'Kab. Mamuju',
 'Kab. Majene',
 'Kab. Maluku Tengah',
 'Kota Ambon',
 'Kota Tual',
 'Kab. Halmahera Tengah',
 'Kota Ternate',
 'Kota Jayapura',
 'Kab. Manokwari',
 'Kab. Merauke',
 'Kab. Nabire',
 'Kab. Mimika',
 'Kab. Jayawijaya',
 'Kab. Sorong',
 'Kab. Sorong Selatan',
 'Kota Sorong']

// export const cropType = [
//   "Barley",
//   "Cotton",
//   "Ground Nuts",
//   "Maize",
//   "Millets",
//   "Oil seeds",
//   "Paddy",
//   "Pulses",
//   "Sugarcane",
//   "Tobacco",
//   "Wheat",
// ];

// export const soilType = ["Black", "Clayey", "Loamy", "Red", "Sandy"];

export const cropType = [
  "Jelai",
  "Kapas",
  "Kacang Tanah",
  "Jagung",
  "Jewawut / Serealia kecil",
  "Oil seeds",
  "Padi",
  "Kacang-kacangan",
  "Tebu",
  "Tembakau",
  "Gandum",
];

export const soilType = ["Hitam", "Liat", "Lempung", "Merah", "Berpasir"];
