version: "3.8"

services:
  map:
    image: ${IMAGE_VERSION}
    networks:
      - code-overlay
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
networks:
  code-overlay:
    external: true
